### ISSUE TITLE
Chef::Exceptions::CookbookNotFound: Cookbook zabbix not found. If you're loading zabbix from another cookbook, make sure you configure the dependency in your metadata

### ISSUE THREAD

**Issue by ncostis** [laradji/zabbix#124]
I am trying to install the cookbook in ubuntu 12.10 and i get 
root@cyclops:~# chef-client
[Mon, 16 Dec 2013 12:36:38 +0200] INFO: **\* Chef 10.12.0 ***
[Mon, 16 Dec 2013 12:36:39 +0200] INFO: Run List is [recipe[zabbix-master]]
[Mon, 16 Dec 2013 12:36:39 +0200] INFO: Run List expands to [zabbix-master]
[Mon, 16 Dec 2013 12:36:39 +0200] INFO: Starting Chef Run for cyclops.gt.central
[Mon, 16 Dec 2013 12:36:39 +0200] INFO: Running start handlers
[Mon, 16 Dec 2013 12:36:39 +0200] INFO: Start handlers complete.
[Mon, 16 Dec 2013 12:36:39 +0200] INFO: Loading cookbooks [apache2, apt, ark, aws, bluepill, build-essential, chef_handler, chocolatey, database, firewall, mysql, nginx, ohai, openssl, php-fpm, postgresql, powershell, rsyslog, runit, ufw, windows, xfs, yum, zabbix-master]
[Mon, 16 Dec 2013 12:36:41 +0200] INFO: Powershell light-weight provider already initialized -- overriding!
[Mon, 16 Dec 2013 12:36:41 +0200] INFO: Powershell light-weight resource already initialized -- overriding!
[Mon, 16 Dec 2013 12:36:42 +0200] ERROR: Running exception handlers
[Mon, 16 Dec 2013 12:36:42 +0200] FATAL: Saving node information to /var/chef/cache/failed-run-data.json
[Mon, 16 Dec 2013 12:36:42 +0200] ERROR: Exception handlers complete
[Mon, 16 Dec 2013 12:36:42 +0200] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[Mon, 16 Dec 2013 12:36:42 +0200] FATAL: Chef::Exceptions::CookbookNotFound: Cookbook zabbix not found. If you're loading zabbix from another cookbook, make sure you configure the dependency in your metadata

in the chef-stacktrace.out i get 
Chef::Exceptions::CookbookNotFound: Cookbook zabbix not found. If you're loading zabbix from another cookbook, make sure you configure the dependency in your metadata
and lot more.

Can anyone help?

Thanks 
Nick

**Comment by ee10b083** [comment]
@ncostis Can you tell me how you were able to solve this problem, as i was using zabbix  0.8.0 and still facing this problem
