### ISSUE TITLE
Dependency overload

### ISSUE THREAD

**Issue by TD-4242** [laradji/zabbix#189]
Would it be worth while to break this cookbook up into 4 different cookbooks?  Installing the agent seems to pull in a lot of unneeded attributes and cookbooks.

I'm thinking:

zabbix-agent - with agent and depend agent specific dependencies
zabbix-server - with server and depend on server specific dependencies
zabbix-web - with front-end and depend on web specific dependencies

Or is there a trick I don't know to help manage this?

**Comment by poliva83** [comment]
+1

**Comment by TD-4242** [comment]
I have the zabbix-agent cookbook pretty well fleshed out.  Just adding testing and support for all platforms supported by test kitchen.  I also have a zabbix-server and zabbix-web repo in my github but they are no where near ready for use.  As I get time I'll be working on them though.

I also moved all the lwrps to libzabbix cookbook.  All together you should be able to deploy with only minimal dependencies.

**Comment by poliva83** [comment]
@TD-4242 Are you planning on releasing new version of zabbix-agent and then uploading to supermarket soon? I'd like to depend on your cookbook instead of this one when installing only the agent.

**Comment by TD-4242** [comment]
it is in the supermarket now.

https://supermarket.chef.io/cookbooks/zabbix-agent

**Comment by poliva83** [comment]
@TD-4242 I was talking about 0.13.0 but after reviewing all the commits since 0.12.0 release they seem mostly all documentation changes. I'll proceed with 0.12.0.

**Comment by TD-4242** [comment]
Yes, I've just been working on documentation and kitchen testing.  Minor changes to support fedora and systemd are currently on my workbench.  I don't personally use either so the priority is pretty low.
