### ISSUE TITLE
Cookbook is not working properly at all

### ISSUE THREAD

**Issue by gesteves91** [laradji/zabbix#217]
Some of the recipes that you've been using inside your cookbook are not used in that way anymore. For instance, database::mysql doesn't exist anymore.

If I try adding your cookbook in a run-list that I've created to install zabbix. It doesn't work.

Database and MySql cookbook don't run in that way anymore. Database doesn't have a mysql recipe, e.g.

**Comment by hpeti2** [comment]
Let's see #206 .
