### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by davidcpell** [laradji/zabbix#220]
Hi! I just started using the cookbook today and was going to submit a small PR but then noticed that there are a number of issues/PRs from last year with no resolution and no commits in several months. Just wanted to see if this project is being actively maintained before submitting something or (if not) possibly forking. Thanks!

**Comment by laradji** [comment]
hey @davidcpell ,

you can fork, i'm looking for a maintainer or a pool of maintainer for some times with no succes
